Calculator
TonyKim9401/justin-racing pull request #1
Opened 2024-08-31 04:03 UTC by TonyKim9401

His bat is waiting...

2024-09-01 04:32 UTC, liquidjoo requested changes
thank you for trying this quiz
I have left a few comments after reviewing it
I look forward to your feedback 🙇

2024-09-01 04:32 UTC, liquidjoo commented on src/main/java/org/calculator/Calculator.java
> +}
Can you tell why this code was made into interface?
> What impact could this code have?

2024-09-01 04:32 UTC, liquidjoo commented on src/main/java/org/calculator/FourBaseArithmeticCalculator.java
> +public class FourBaseArithmeticCalculator implements Calculator {
What do you think about the code not having a constructor?

2024-09-01 04:32 UTC, liquidjoo commented on src/main/java/org/calculator/FourBaseArithmeticCalculator.java
> +public class FourBaseArithmeticCalculator implements Calculator {
What could happens if the code doesn't have a constructor?

2024-09-01 04:32 UTC, liquidjoo commented on src/main/java/org/calculator/FourBaseArithmeticCalculator.java
> +    }
I think these methods might not need a constructor, right?
How would you modify these?

2024-09-01 04:32 UTC, liquidjoo commented on src/main/java/org/calculator/FourBaseArithmeticCalculator.java
> +    }
You should think about the role & responsibility of this method

2024-09-01 04:32 UTC, liquidjoo commented on src/main/java/org/calculator/Calculator.java
> +}
You should search for java naming conventions

2024-09-01 04:32 UTC, liquidjoo commented on src/main/java/org/calculator/FourBaseArithmeticCalculator.java
> +    }
You should think about the role & responsibility of this method
> You can't use switch; switch is the same as using multiple if statements.
> How could you solve this problem?

2024-09-01 04:32 UTC, liquidjoo commented on src/test/java/org/calculator/FourBaseArithmeticCalculatorTest.java
> +    }
if you create a test code, you should define fields (excepted, actual),
and then you can compare the expect and actual fields.

2024-09-03 05:31 UTC, TonyKim9401 commented on src/main/java/org/calculator/Calculator.java
> +}
https://velog.io/@9ruem2/Naming-Conventions-%EC%9E%90%EB%B0%94-%EB%84%A4%EC%9D%B4%EB%B0%8D%EA%B7%9C%EC%B9%99-%EC%A0%95%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95
네이밍 컨벤션 적용해보았습니다!

2024-09-03 05:32 UTC, TonyKim9401 commented on src/main/java/org/calculator/FourBaseArithmeticCalculator.java
> +public class FourBaseArithmeticCalculator implements Calculator {
기본 생성자가 없으면 클래스 생성시 자동으로 기본 생성자를 만들어 주죠, 이걸 물어보신건 아닌것 같은데.. 요지 파악을 못한것 같습니다.

2024-09-03 05:32 UTC, TonyKim9401 commented on src/main/java/org/calculator/FourBaseArithmeticCalculator.java
> +    }
ENUM으로 바꿔보았습니다. 근데 여기서 메소드에 생성자가 필요없다고 하신건 어떤 말씀이신지 잘 모르겟습니다.

2024-09-03 05:33 UTC, TonyKim9401 commented on src/main/java/org/calculator/FourBaseArithmeticCalculator.java
> +    }
분리하였습니다.

2024-09-03 05:33 UTC, TonyKim9401 commented on src/main/java/org/calculator/FourBaseArithmeticCalculator.java
> +    }
분리하였습니다.

2024-09-03 05:33 UTC, TonyKim9401 commented on src/test/java/org/calculator/FourBaseArithmeticCalculatorTest.java
> +    }
expected와 actual로 나누어서 리팩토링 해보았는데, 예시가 있으면 더 좋을것 같습니다 ㅜ..

2025-01-03 05:44 UTC, liquidjoo approved these changes
다음 단계 진행해봅시다!

2025-01-03 05:44 UTC, merged